### ISSUE TITLE
release 0.4.2 undocumentedly breaks python <3.6 compatibility

### ISSUE THREAD

**Issue by jribbens** [googleapis/google-auth-library-python-oauthlib#101]
Release 0.4.2 of this package breaks compatibility with all Python versions before 3.6. That is obviously something that is within your prerogative to do. However:

* it should be documented in `CHANGELOG.md`
* it should be documented in `README.rst`
* it should not happen in a patch release
* it should not happen in a commit whose message is "fix: don't open browser if port is occupied"

**Comment by busunkim96** [comment]
Hi @jribbens,

Thanks for the feedback and apologies for any confusion it may have caused. This repo sat untouched for a while, so I rolled a lot of cleanup items into https://github.com/googleapis/google-auth-library-python-oauthlib/commit/00040576ab096faec1f6eb54c886cb9c33be17ed  that admittedly should have been done in separate commits.

> - it should be documented in CHANGELOG.md

Yep, we'll make sure dropped versions get documented in the CHANGELOG next time.

> - it should be documented in README.rst

We don't currently maintain a list of supported Python versions in the README so I'm not sure this is relevant. Would a 'supported versions' badge like the one in [python-api-core](https://github.com/googleapis/python-api-core#core-library-for-google-client-librariese) be useful?

> - it should not happen in a patch release

Looking through some other libraries our team maintains I think we usually drop versions in a minor release after the Python version has gone EOL ([example](https://github.com/googleapis/python-api-core/blob/master/CHANGELOG.md#1240-2020-12-14)). Does that seem appropriate to you? The list of currently supported version is reflected in the version classifiers and `python_requires`.

https://github.com/googleapis/google-auth-library-python-oauthlib/blob/7638659586a91354d92a3b11ea4d02434ac5e59a/setup.py#L48

> -  it should not happen in a commit whose message is "fix: don't open browser if port is occupied"

Ack, I did a poor job of properly documenting all the changes in https://github.com/googleapis/google-auth-library-python-oauthlib/commit/00040576ab096faec1f6eb54c886cb9c33be17ed

**Comment by jribbens** [comment]
The most important thing from my personal point of view is to document things like this in `CHANGELOG.md`, so that when I do a `pip install -r requirements.txt` and I get errors it's not too hard to find out what `<x.y` I need to be adding to the requirements list.

In an ideal world you'd be using semver and a change like this would clearly be a major version increase (because then everyone could make a reasonable guess at how to future-proof their projects by putting `google-auth-oauthlib>=0.4,<1` or whatever), but I guess you're not and I don't expect you to make a policy change like that on my say so ;-)

I do think documenting basic requirements like "Needs Python >=3.6" in the README would be useful for newcomers to the package though.

**Comment by busunkim96** [comment]
I was hoping [python_requires](https://packaging.python.org/guides/dropping-older-python-versions/#dropping-a-python-release) would be enough to prevent accidental installs - but point taken that it's best to make the supported python versions visible in multiple places. 👍 

I think we (maintainers of google-cloud-python libraries) need to sit down and come up with a written policy on how we'll drop Python versions in the future.

(This is a tangent; just writing this down here to record my thoughts. 😄 )

The 2.7 drops in the google-cloud-* libraries had other breaking changes in their interface so they were released as new major versions.

Subsequent 3.x minor drops have happened in minor library releases. The rationale was there were no other  'breaking' API changes, and we expect folks to be protected from surprise upgrades via `python_requires`. Because many google packages share common dependencies, releasing major versions can cause diamond dependency issues. [Apache Beam docs](https://beam.apache.org/contribute/dependencies/) explain this briefly.

If we decide that dropping support for a minor version of Python constitutes a major change, that would require a new major version every year given the [Python release cadence](https://www.python.org/dev/peps/pep-0602/#annual-release-cadence). We would need to come up with some way of coordinating releases to minimize the version conflicts end users see.

**Comment by jribbens** [comment]
It appears on further investigation that support for `python_requires` depends on what version of `pip` you have ;-) So _most_ people will probably be protected from errors, but perhaps not if they're using Ubuntu 16 (which is still in support for another 3 years...) I stand by the comments I made at the top of this thread, but the impact on most people will probably be less than it was for us!
