### ISSUE TITLE
 The flow.run_console() function cannot be found.

### ISSUE THREAD

**Issue by Pumi1a** [googleapis/google-auth-library-python-oauthlib#285]
The reason is that the run_console() function does not exist in the source code of the installed google-auth-library-python-oauthlib. Specifically, the source code of site-packages/google_auth_oauthlib/flow.py differs from the published source code.
The published source code is as follows.
https://google-auth-oauthlib.readthedocs.io/en/latest/_modules/google_auth_oauthlib/flow.html#InstalledAppFlow.run_console
In this code, '_OOB_REDIRECT_URI = "urn:ietf:wg:oauth:2.0:oob"' and 'def run_console(' are not defined (around line 359).
You can manually add them and use the run_console() function.
Thank you for your attention.

**Comment by sai-sunder-s** [comment]
OOB flow was deprecated in https://github.com/googleapis/google-auth-library-python-oauthlib/commit/1fb16be1bad9050ee29293541be44e41e82defd7. Use `run_local_server()` instead of `run_console()`.

The deprecated code was removed in https://github.com/googleapis/google-auth-library-python-oauthlib/commit/13914865ec3cbdb1e4ab87a7bcfc34d0b4e184d3

Please reopen if that doesn't answer your question.

**Comment by adriel** [comment]
What do people do if they don't have local browser access? (e.g. running on a headless server)

**Comment by marfer** [comment]
> What do people do if they don't have local browser access? (e.g. running on a headless server)

I guess you need to write your own implementation. 
Limited-Input Device authentication flow can work well for this scenario: https://developers.google.com/identity/protocols/oauth2/limited-input-device
Here is a good example: https://github.com/lila/python-simple-mqtt-k3s/blob/main/src/OAuth2.py
