### ISSUE TITLE
InstalledAppFlow for web applications

### ISSUE THREAD

**Issue by mafrosis** [googleapis/google-auth-library-python-oauthlib#341]
Hi there

I'm working with a Google Calendar library which imports this library as a helper for the oauth flow. 

I found that since last time I did this, the OOB flow is now deprecated. So, I was fiddling with redirects and trying to get something working. I'm working on a web app, but this library implements `run_local_server` to start a local webserver..

So, it seems that this library is aimed at the desktop flow only? Or am I missing something?

Thanks!

**Comment by arithmetic1728** [comment]
If you have an endpoint listening to the redirect url, probably you can use this class https://github.com/googleapis/google-auth-library-python-oauthlib/blob/main/google_auth_oauthlib/flow.py#L98 to set up the redirect url.

We haven't done anything like this before because our main focus is desktop applications.

**Comment by mafrosis** [comment]
Thanks, makes sense. I might open a PR if it makes in the library - otherwise I'll implement the flow in the calendar library.. or directly in my app.
