### ISSUE TITLE
Unable to authenticate using  google-oauthlib-tool 

### ISSUE THREAD

**Issue by beer-to-code** [googleapis/google-auth-library-python-oauthlib#370]
(env) pi@jarvis:~ $ google-oauthlib-tool --client-secrets ./client_secret_858487554047-4corgtdi0ritlrs6.apps.googleusercontent.com.json --scope https://www.googleapis.com/auth/assistant-sdk-prototype --scope https://www.googleapis.com/auth/gcm --save --headless
Error: no such option: --headless

**Comment by clundin25** [comment]
I don't think `--headless` is documented as a support flag. Where is this command sourced from?

**Comment by westarle** [comment]
`--headless` was removed in #264 because the OAuth feature it relied on (out-of-band) was [turned down](https://developers.googleblog.com/en/making-google-oauth-interactions-safer-by-using-more-secure-oauth-flows/#disallowed-oob) for security reasons.

I'm not aware of another general OAuth method to provide a headless experience like the one offered by `--headless`.
