### ISSUE TITLE
Need more documentation on how to use the library

### ISSUE THREAD

**Issue by zmunro** [googleapis/google-auth-library-python-oauthlib#53]
It would be helpful to have more information and practical examples of how to use this library

**Comment by busunkim96** [comment]
Hi @zmunro, apologies for the frustration caused by our documentation. We are aware that there is room for it to be improved. However, I want to call attention that the way you're expressing your frustration is not acceptable as per our code of conduct. We're happy to help, but please treat this space and the people within it with respect.

Our documentation lives here: https://google-auth-oauthlib.readthedocs.io/en/latest/reference/modules.html


* Documentation on application authorization flows: https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html
* Helpers for integrating with requests-oauthlib: https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.helpers.html

Please provide additional detail on what you're looking to do and we can help.
